apiVersion: v1
kind: Pod
metadata:
  name: testpod3
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/sh", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/sh", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]

